---

- name: Refresh yum metadata
  ansible.builtin.command: yum makecache
  become: yes
  changed_when: true

- name: Show Python version used by Ansible
  command: "{{ ansible_python_interpreter }} --version"
  register: python_version_output

- name: Display Python version
  debug:
    msg: "{{ python_version_output.stdout }}"


- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present
  become: yes
  vars:
    ansible_pkg_mgr: yum

- name: Enable and start Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy Nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

