---
- name: Install python3.8
  raw: |
    sudo amazon-linux-extras enable python3.8 && \
    sudo yum install -y python3.8

- name: Refresh yum metadata
  ansible.builtin.dnf:
    update_cache: yes
    use_backend: dnf4


- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Enable and start Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy Nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

