# SPDX-License-Identifier: MIT-0
# vars file for server
# vars/main.yml

# SPDX-License-Identifier: MIT-0
# vars file for server
# vars/main.yml

tf_outputs: "{{ lookup('file', playbook_dir + '/roles/app/vars/db.json') | from_json }}"
db_host: "{{ tf_outputs.db_host }}"
db_user: "{{ tf_outputs.db_user }}"
db_password: "{{ tf_outputs.db_password }}"
db_name: "{{ tf_outputs.db_name }}"
db_port: 3306  # default MySQL port





