- name: Add NodeSource GPG key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource Node.js repo for Ubuntu 22.04 (jammy)
  ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
  args:
    executable: /bin/bash


- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes


- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present
    update_cache: yes


- name: Create node user if not exists
  ansible.builtin.user:
    name: node
    system: yes
    create_home: no
    shell: /usr/sbin/nologin

- name: Create systemd service for Node.js app
  ansible.builtin.copy:
    dest: /etc/systemd/system/onet-gaming.service
    content: |
      [Unit]
      Description=My Node.js App
      After=network.target

      [Service]
      ExecStart=/usr/bin/node /opt/server/app.js
      Restart=always
      User=node
      Group=node
      Environment=PATH=/usr/bin:/usr/local/bin
      WorkingDirectory=/opt/server

      [Install]
      WantedBy=multi-user.target
