---
- name: Generate .env file for app
  template:
    src: templates/.env.j2
    dest: /var/www/server/.env
    mode: '0600'

- name: Copy Node.js application to server
  ansible.builtin.copy:
    src: server/
    dest: /var/www/server/
    mode: '0644'
    owner: root
    group: root
    directory_mode: '0755'
    
  notify:
    - Restart Node.js App  