---
- name: Ensure app directory exists
  file:
    path: /opt/server
    state: directory
    owner: root
    group: root
    mode: '0755'


- name: Generate .env file for app
  template:
    src: templates/.env.j2
    dest: /opt/server/.env
    mode: '0600'


- name: Archive Node.js app
  local_action:
    module: archive
    path: ./server
    dest: /tmp/server.tar.gz

- name: Copy archive to server
  copy:
    src: /tmp/server.tar.gz
    dest: /tmp/server.tar.gz

- name: Extract app on server
  unarchive:
    src: /tmp/server.tar.gz
    dest: /opt/
    remote_src: yes



    
  notify:
    - Restart Node.js App  