---
- name: Ensure app directory exists
  file:
    path: /opt/server
    state: directory
    owner: root
    group: root
    mode: '0755'


- name: Generate .env file for app
  template:
    src: templates/.env.j2
    dest: /opt/server/.env
    mode: '0600'


- name: Copy Node.js application to server
  ansible.posix.synchronize:
    src: /server
    dest: /opt/server/
    recursive: yes
    delete: yes


    
  notify:
    - Restart Node.js App  